# Generated by Django 5.2.16 on 2026-08-02 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_complaintfeedback_complaintimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_name', models.CharField(max_length=100, unique=True)),
                ('template', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_payload', models.TextField(blank=True, null=True)),
                ('response_payload', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('execution_time', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_category', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_priority', models.CharField(blank=True, max_length=50, null=True)),
                ('predicted_severity', models.CharField(blank=True, max_length=50, null=True)),
                ('predicted_department', models.CharField(blank=True, max_length=100, null=True)),
                ('short_summary', models.TextField(blank=True, null=True)),
                ('detailed_summary', models.TextField(blank=True, null=True)),
                ('officer_summary', models.TextField(blank=True, null=True)),
                ('citizen_summary', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('execution_time', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('sentiment', models.CharField(default='Neutral', max_length=50)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='complaints.complaint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(max_length=20)),
                ('predicted_field', models.CharField(max_length=50)),
                ('corrected_value', models.CharField(blank=True, max_length=255, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedbacks', to='complaints.complaint')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
